### ISSUE TITLE
Chassis ComputerSystems field is handled improperly

### ISSUE THREAD

**Issue by keithwegner** [Comcast/fishymetrics#68]
It appears as though `Chassis.Links.ComputerSystems` is not being parsed/unmarshalled correctly. When running a query against the `dmtf/redfish-mockup-server`, we receive an error:

> Error Unmarshalling Chassis struct - json: cannot unmarshal object into Go struct field ChassisLinks.Links.ComputerSystems of type string"

To reproduce this, run the Redfish Mockup Server Docker container:
`docker run --rm -d -p 8000:8000 dmtf/redfish-mockup-server:latest`

And then run a Fishymetrics container:
`docker run -p 9533:9533 -e BMC_USERNAME=admin -e BMC_PASSWORD=password -e EXPORTER_PORT=9533 -e BMC_TIMEOUT=15s -e BMC_SCHEMD=http comcast/fishymetrics`.

You can now curl the Fishymetrics endpoint:
`curl localhost:9533/scrape?target=http://localhost:8000` and will see the error.

The DMTF Redfish Mockup Server uses the "[Simple Rack-mounted Server](https://redfish.dmtf.org/redfish/mockups/v1/1448)" mockup for its data, which is also found here: 
https://github.com/DMTF/Redfish-Mockup-Server/blob/main/public-rackmount1/Chassis/1U/index.json. The full index.json is posted at the bottom of this issue.

The DMTF specification shows the `Chassis.Links.ComputerSystems` as follows:

```
    "Links": {
        "ComputerSystems": [
            {
                "@odata.id": "/redfish/v1/Systems/437XR1138R2"
            }
        ],
```

That is what fails. 

If `ComputerSystems` is (incorrectly) changed to the following, it works.
```
    "Links": {
        "ComputerSystems": [
                "/redfish/v1/Systems/437XR1138R2",
                "/redfish/v1/Systems/437XR1138R2"
        ],
```

```
{
    "@odata.type": "#Chassis.v1_25_0.Chassis",
    "Id": "1U",
    "Name": "Computer System Chassis",
    "ChassisType": "RackMount",
    "AssetTag": "Chicago-45Z-2381",
    "Manufacturer": "Contoso",
    "Model": "3500RX",
    "SKU": "8675309",
    "SerialNumber": "437XR1138R2",
    "PartNumber": "224071-J23",
    "PowerState": "On",
    "IndicatorLED": "Lit",
    "HeightMm": 44.45,
    "WidthMm": 431.8,
    "DepthMm": 711,
    "WeightKg": 15.31,
    "Location": {
        "PostalAddress": {
            "Country": "US",
            "Territory": "OR",
            "City": "Portland",
            "Street": "1001 SW 5th Avenue",
            "HouseNumber": 1100,
            "Name": "DMTF",
            "PostalCode": "97204"
        },
        "Placement": {
            "Row": "North",
            "Rack": "WEB43",
            "RackOffsetUnits": "EIA_310",
            "RackOffset": 12
        }
    },
    "Status": {
        "State": "Enabled",
        "Health": "OK"
    },
    "ThermalSubsystem": {
        "@odata.id": "/redfish/v1/Chassis/1U/ThermalSubsystem"
    },
    "PowerSubsystem": {
        "@odata.id": "/redfish/v1/Chassis/1U/PowerSubsystem"
    },
    "EnvironmentMetrics": {
        "@odata.id": "/redfish/v1/Chassis/1U/EnvironmentMetrics"
    },
    "Sensors": {
        "@odata.id": "/redfish/v1/Chassis/1U/Sensors"
    },
    "Controls": {
        "@odata.id": "/redfish/v1/Chassis/1U/Controls"
    },
    "TrustedComponents": {
        "@odata.id": "/redfish/v1/Chassis/1U/TrustedComponents"
    },
    "Thermal@Redfish.Deprecated": "Please migrate to use /redfish/v1/Chassis/1U/ThermalSubsystem",
    "Thermal": {
        "@odata.id": "/redfish/v1/Chassis/1U/Thermal"
    },
    "Power@Redfish.Deprecated": "Please migrate to use /redfish/v1/Chassis/1U/PowerSubsystem",
    "Power": {
        "@odata.id": "/redfish/v1/Chassis/1U/Power"
    },
    "Links": {
        "ComputerSystems": [
            {
                "@odata.id": "/redfish/v1/Systems/437XR1138R2"
            }
        ],
        "ManagedBy": [
            {
                "@odata.id": "/redfish/v1/Managers/BMC"
            }
        ],
        "ManagersInChassis": [
            {
                "@odata.id": "/redfish/v1/Managers/BMC"
            }
        ]
    },
    "@odata.id": "/redfish/v1/Chassis/1U",
    "@Redfish.Copyright": "Copyright 2014-2023 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright."
}
```

**Comment by derrick-dacosta** [comment]
Hi @keithwegner thank you for finding this. Also, I did not know about the `dmtf/redfish-mockup-server` app, so thank you again for showing me that! We can definitely use it to improve the testcases for this project.

The issue you found is because we didn't account for the extra spaces within the json response. I've improved the unmarshalling function to better handle the different possible responses. Unfortunately in our environments we have to deal with older and newer versions of the redfish API.

This PR #70 should fix your issue.

**Comment by keithwegner** [comment]
Happy to help! I was about to offer up another fix that may be a bit cleaner (though I don't have all of the details on your side):

I've used used the [`json.Compact()`] (https://pkg.go.dev/encoding/json#Compact:~:text=Functions%20%C2%B6-,func%20Compact%20%C2%B6,-func%20Compact(dst)) function. I'm not sure about any performance tradeoffs, but I like that it doesn't rely on error handling. 

```
var buf bytes.Buffer
json.Compact(&buf, data)
data = buf.Bytes()
```

```
func (w *LinksWrapper) UnmarshalJSON(data []byte) error {
	// because of a change in output between firmware versions we need to account for this
        var buf bytes.Buffer
        json.Compact(&buf, data)
        data = buf.Bytes()
	if bytes.Compare([]byte("[{"), data[0:2]) == 0 {
		var linksTmp []struct {
			URL  string `json:"@odata.id,omitempty"`
			HRef string `json:"href,omitempty"`
		}
		err := json.Unmarshal(data, &linksTmp)
		if len(linksTmp) > 0 {
			for _, l := range linksTmp {
				if l.URL != "" {
					w.LinksURLSlice = append(w.LinksURLSlice, l.URL)
				} else {
					w.LinksURLSlice = append(w.LinksURLSlice, l.HRef)
				}
			}
			return nil
		}
		return err
	}
	return json.Unmarshal(data, &w.LinksURLSlice)
}
```

**Comment by derrick-dacosta** [comment]
My initial plan was to remove the unnecessary space characters like what you've shown, but after some thought, I would get cleaner code if I just let `json.Unmarshal()` deal with the  byte comparisons. In another PR I need to handle the cases where the response is a `[]struct{}` but errored the unmarshal due to something unforeseen. Instead of just assuming the response is then a `[]string` and then debugging it that way.
