### ISSUE TITLE
add support for Dell model chassis

### ISSUE THREAD

**Issue by derrick-dacosta** [Comcast/fishymetrics#77]
We will track all development progress as well as bugs/features during this effort in this issue.

**Comment by ibrahimkk-moideen** [comment]
Included support for few Dell server models in https://github.com/Comcast/fishymetrics/pull/80.

**Comment by derrick-dacosta** [comment]
#84

**Comment by ibrahimkk-moideen** [comment]
https://github.com/Comcast/fishymetrics/pull/86

**Comment by ibrahimkk-moideen** [comment]
This is complete. Added support and tested with below PowerEdge models

r640, r6515, r720xd, r730xd, r7515 & r7615.
