### ISSUE TITLE
Docker image no longer available?

### ISSUE THREAD

**Issue by keithwegner** [Comcast/fishymetrics#78]
Did the location of the image change? It seems like running `docker pull comcast/fishymetrics` no longer completes.

**Comment by derrick-dacosta** [comment]
Unfortunately the image has not make it to that location yet. The intention was to make and supply the image to `comcast/fishymetrics` but in doing that it would be considered software distribution. We are working with legal and security on our side to be able to safely provide a built image for users to have in their deployments.

**Comment by derrick-dacosta** [comment]
Hi @keithwegner great news, we are able to publish the docker image in docker hub now. Please see our latest tagged version, https://hub.docker.com/r/comcast/fishymetrics/tags

Closing the issue.
